export const CLIP_SEQUENCE = [
  {
    id: 'main',
    label: 'Sketch and pencil portal',
    src: 'imports/paper-portal/transition-draft-v01/01-full-sequence-current-keeper.mp4',
    durationFrames: 631,
    accent: '#ffe8a3',
    baseVolume: 1,
  },
  {
    id: 'pixel',
    label: 'Pixel world',
    src: 'imports/paper-portal/transition-draft-v01/02-pixel-world.mp4',
    durationFrames: 240,
    accent: '#ffd95d',
    baseVolume: 0.82,
  },
  {
    id: 'neon',
    label: 'Neon arcade world',
    src: 'imports/paper-portal/transition-draft-v01/03-neon-arcade-world.mp4',
    durationFrames: 125,
    accent: '#29e7ff',
    baseVolume: 0.82,
  },
  {
    id: 'storybook',
    label: 'Soft 3D storybook world',
    src: 'imports/paper-portal/transition-draft-v01/04-soft-3d-storybook-world.mp4',
    durationFrames: 136,
    accent: '#ffe49c',
    baseVolume: 0.82,
  },
  {
    id: 'japanese',
    label: 'Hand-painted Japanese fantasy',
    src: 'imports/paper-portal/transition-draft-v01/05-hand-painted-japanese-fantasy.mp4',
    durationFrames: 135,
    accent: '#fff0b8',
    baseVolume: 0.82,
  },
  {
    id: 'plush',
    label: 'Plush toy diorama',
    src: 'imports/paper-portal/transition-draft-v01/06-plush-toy-diorama-world.mp4',
    durationFrames: 125,
    accent: '#ffd7a8',
    baseVolume: 0.82,
  },
  {
    id: 'clay',
    label: 'Stop-motion clay cutout',
    src: 'imports/paper-portal/transition-draft-v01/07-stop-motion-clay-cutout-world.mp4',
    durationFrames: 125,
    accent: '#ffe6a1',
    baseVolume: 0.82,
  },
];
